name = "nice-analytics"
main = "src/worker.js"
compatibility_date = "2026-06-12"
workers_dev = false
preview_urls = false
routes = [
  { pattern = "analytics.nice.okinawa/*", zone_name = "nice.okinawa" }
]

[triggers]
crons = ["18 20 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "nice_analytics"
database_id = "fbcc9bc2-3556-4ac4-8168-8611940114d3"

[vars]
ALLOWED_ORIGIN = "https://translation.nice.okinawa"
DASHBOARD_ORIGIN = "https://db.nice.okinawa"
GSC_SITE_URLS = "https://translation.nice.okinawa/,https://nice.okinawa/,https://golf.nice.okinawa/,https://fishing.nice.okinawa/,https://rental.nice.okinawa/,https://snorkel.nice.okinawa/,https://japanusedcars.nice.okinawa/,https://bjt.nice.okinawa/"
