name = "db-private"
main = "src/worker.js"
compatibility_date = "2026-06-12"
workers_dev = false
preview_urls = false
routes = [
  { pattern = "db.nice.okinawa/*", zone_name = "nice.okinawa" }
]

[vars]
DASHBOARD_ORIGIN = "https://raw.githubusercontent.com/wanjiaoben/db/main"

[[services]]
binding = "ANALYTICS"
service = "nice-analytics"

[[kv_namespaces]]
binding = "BJT_KV"
id = "fc382800625e42b7bbfe13830dd39e82"

[env.preview]
name = "db-private-t0705-12"
workers_dev = true
preview_urls = true
routes = []

[env.preview.vars]
DASHBOARD_ORIGIN = "https://raw.githubusercontent.com/wanjiaoben/db/main"
ANALYTICS_ORIGIN = "https://nice-analytics-t0705-12.gerheidicn.workers.dev"

[[env.preview.services]]
binding = "ANALYTICS"
service = "nice-analytics-t0705-12"

[[env.preview.kv_namespaces]]
binding = "BJT_KV"
id = "4a016f0e1eb94e14a08d6aa53add61e3"
